CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    -- Cognito sub
    auth_user_id VARCHAR(255) NOT NULL UNIQUE,

    -- login email
    email VARCHAR(255) NOT NULL UNIQUE,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

