name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "Makefile"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true

      - name: Run Backend CI
        run: make backend-ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build
        run: make backend-build

      - name: Package
        run: make backend-package

      - name: Upload Artifact
        run: make backend-upload
